import json
import argparse
import subprocess
import shutil
import sys
import os
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading
from rich.prompt import Prompt
from rich.console import Console

console = Console()

# Paths config
DEFAULT_OUTPUT_DIR = Path.home() / "Downloads" / "bunkr_downloads"

# Thread-safe terminal layout lock
stdout_lock = threading.Lock()
# Global tracking for active lines so any thread can trigger a clean block refresh
worker_statuses = []

# Set once Ctrl+C is caught. Worker threads check this before writing to the
# display so nothing lands on the terminal after the layout has been torn down.
shutdown_event = threading.Event()

# Live yt-dlp subprocess handles, so an interrupt can actually kill them
# instead of just cancelling futures that haven't started yet.
active_processes_lock = threading.Lock()
active_processes = {}  # slot_id -> Popen

# Layout globals, computed once at startup (see setup_display_region)
TERMINAL_ROWS = 24
SCROLL_BOTTOM = 24  # last row that belongs to the scrolling history region


def parse_arguments():
    """Parse command line arguments for the downloader script."""
    parser = argparse.ArgumentParser(description="Parallel/Sequential yt-dlp Asset Downloader Queue.")
    parser.add_argument(
        '-i', '--input',
        type=str,
        default=None,
        help=(
            "Path to the enriched album JSON file generated by the scraper. "
            "If omitted, you'll be prompted for it interactively."
        )
    )
    parser.add_argument(
        '-o', '--output',
        type=str,
        default=None,
        help=(
            "Directory to save downloaded files into "
            f"(default: {DEFAULT_OUTPUT_DIR})."
        )
    )
    parser.add_argument(
        '-w', '--workers',
        type=int,
        default=None,  # Set to None to cleanly identify when no CLI argument is given
        help="Number of concurrent download worker threads to spawn."
    )
    parser.add_argument(
        '-n', '--number',
        type=str,
        default=None,
        help=(
            "Restrict the run to specific item(s) from the JSON, by their "
            "1-based position (the same number shown in [n/total] logging). "
            "Accepts a single index ('5'), a comma list ('3,7,12'), a range "
            "('10-20'), or a mix of both ('1,4-6,9'). Omit to download everything."
        )
    )
    return parser.parse_args()


def parse_selection(spec: str, total_files: int) -> set:
    """Parses a -n/--number spec like '1,4-6,9' into a set of 1-based indices."""
    selected = set()
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            start_str, end_str = chunk.split("-", 1)
            start, end = int(start_str), int(end_str)
            if start > end:
                start, end = end, start
            selected.update(range(start, end + 1))
        else:
            selected.add(int(chunk))

    out_of_range = {i for i in selected if i < 1 or i > total_files}
    if out_of_range:
        raise ValueError(
            f"Index/indices {sorted(out_of_range)} out of range "
            f"(file has {total_files} items, valid range is 1-{total_files})."
        )
    return selected


def clean_dragged_path(raw: str) -> str:
    """
    Normalizes a path typed or drag-and-dropped into the terminal.
    Handles: surrounding whitespace, a matching pair of single or double
    quotes wrapped around the whole thing (common when a terminal
    auto-quotes a dropped file), and backslash-escaped spaces some
    terminals (e.g. macOS Terminal, iTerm) insert for drag-and-drop.
    """
    text = raw.strip()
    if len(text) >= 2 and text[0] == text[-1] and text[0] in ("'", '"'):
        text = text[1:-1].strip()
    # Undo backslash-escaped spaces from drag-and-drop, e.g. "My\ File.json"
    text = text.replace("\\ ", " ")
    return text


def prompt_for_inputs():
    """
    Scans the working directory for payload JSONs, prints them out cleanly,
    and then prompts the user dynamically for input path, items selection, and workers[cite: 5].
    """
    # 1. Scan and print local .json files[cite: 5]
    try:
        json_files = [f for f in os.listdir('.') if f.endswith('.json') and os.path.isfile(f)]
        if json_files:
            console.print("\n[bold magenta][*] Discovered payload JSON targets in working directory:[/bold magenta]")
            for f in sorted(json_files):
                console.print(f"  • [yellow]{f}[/yellow]")
            console.print()
    except Exception as e:
        console.print(f"[bold red][-][/bold red] Warning: Could not scan directory for JSON files: {e}")

    # 2. Prompt for path to the album JSON
    input_path = None
    while True:
        raw = Prompt.ask("[bold cyan][?][/bold cyan] Path to the album JSON file")
        candidate = Path(clean_dragged_path(raw)).expanduser()
        if candidate.exists() and candidate.is_file():
            input_path = candidate
            break
        console.print(f"[bold red][-][/bold red] Error: '{candidate}' doesn't exist or isn't a file. Try again.")

    # 3. Prompt for targeted index selection (subset vs all)
    selection = Prompt.ask(
        "[bold cyan][?][/bold cyan] Enter item index, list, or range [dim](e.g. 5 | 3,7,12 | 1-10 or Press Enter for ALL)[/dim]"
    ).strip()
    if not selection or selection.lower() == 'all':
        selection = None

    # 4. Prompt for worker concurrency
    workers_input = Prompt.ask(
        "[bold cyan][?][/bold cyan] Enter worker concurrency (MAX=5) [dim](Press Enter for default)[/dim]"
    ).strip()
    
    workers = 1
    if workers_input:
        try:
            workers = max(1, int(workers_input))
        except ValueError:
            console.print("[bold yellow][!][/bold yellow] Invalid worker layout pattern. Defaulting to 1 worker.")
            workers = 1

    return input_path, selection, workers


def truncate_to_fit(text: str, max_len: int) -> str:
    """Shortens text with a trailing ellipsis if it won't fit in max_len chars."""
    if max_len <= 1:
        return text[:max_len]
    if len(text) <= max_len:
        return text
    return text[:max_len - 1].rstrip() + "…"


def sanitize_filename(name: str) -> str:
    """Removes or replaces characters that are illegal in Windows/Linux file systems."""
    return "".join(c for c in name if c.isalnum() or c in "._- ()").strip()


def setup_display_region(total_workers: int):
    """
    Reserves the bottom `total_workers` rows of the terminal as a fixed footer
    and restricts scrolling (DECSTBM) to everything above it. Text printed
    normally will now only ever scroll within that upper region -- the footer
    rows are physically untouched by scrolling, so there's no more cursor-math
    to get wrong.
    """
    global TERMINAL_ROWS, SCROLL_BOTTOM
    cols, rows = shutil.get_terminal_size(fallback=(120, 24))
    TERMINAL_ROWS = rows
    # Leave at least a couple of rows for scrolling history even on tiny terminals
    SCROLL_BOTTOM = max(rows - total_workers, 2)

    # Set scroll region to rows [1, SCROLL_BOTTOM]
    sys.stdout.write(f"\033[1;{SCROLL_BOTTOM}r")
    # Park the cursor at the bottom of the scroll region so the next normal
    # print lands right above the footer.
    sys.stdout.write(f"\033[{SCROLL_BOTTOM};1H")
    sys.stdout.flush()


def teardown_display_region():
    """Restores full-screen scrolling and leaves the cursor in a sane spot."""
    sys.stdout.write("\033[r")  # reset scroll region to the whole screen
    sys.stdout.write(f"\033[{TERMINAL_ROWS};1H\n")
    sys.stdout.flush()


def write_history_line(text: str):
    """
    Appends a permanent line (a completed/skipped/failed download) to the
    scrolling history region. Because the scroll region excludes the footer,
    this can never overwrite a worker's status row.
    """
    if shutdown_event.is_set():
        return
    with stdout_lock:
        if shutdown_event.is_set():
            return
        sys.stdout.write(f"\033[{SCROLL_BOTTOM};1H")
        sys.stdout.write("\033[2K")
        sys.stdout.write(text + "\n")
        sys.stdout.flush()


def update_worker_slot(slot_id: int, text: str, total_workers: int):
    """
    Updates exactly one worker's footer row via absolute cursor positioning,
    then restores wherever the cursor was. No dependence on which other slot
    last wrote something.
    """
    if shutdown_event.is_set():
        return
    worker_statuses[slot_id] = text
    row = TERMINAL_ROWS - total_workers + slot_id + 1
    with stdout_lock:
        if shutdown_event.is_set():
            return
        sys.stdout.write("\033[s")               # save cursor position
        sys.stdout.write(f"\033[{row};1H\033[2K{text}")
        sys.stdout.write("\033[u")                # restore cursor position
        sys.stdout.flush()


def execute_ytdlp_task(index: int, total_files: int, file_item: dict, slot_id: int, total_workers: int):
    """Assembles and executes the yt-dlp subprocess payload for a specific asset row."""
    title = file_item.get("title", f"file_{index}")
    cdn_url = file_item.get("signed_cdn_url")

    safe_name = sanitize_filename(title)
    dest = DEFAULT_OUTPUT_DIR / safe_name

    if not cdn_url:
        write_history_line(f"[-] [{index}/{total_files}] Skipping: {safe_name} (No active signed URL found)")
        update_worker_slot(slot_id, f"[Worker {slot_id + 1}] Idle...", total_workers)
        return False

    ytdlp_cmd = [
        "yt-dlp",
        "--no-playlist",
        "--retries", "50",
        "--fragment-retries", "10",
        "--retry-sleep", "5",
        "--concurrent-fragments", "1",
        "--socket-timeout", "25",
        "--continue",
        "--newline",
        "--referer", "https://bunkr.cr/",
        "--add-header", "Origin:https://bunkr.cr",
        "--add-header", (
            "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "--add-header", "Accept-Encoding:identity",
        "-o", str(dest),
        cdn_url,
    ]

    process = None
    try:
        process = subprocess.Popen(ytdlp_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, encoding="utf-8")
        with active_processes_lock:
            active_processes[slot_id] = process

        if process.stdout:
            for line in process.stdout:
                if shutdown_event.is_set():
                    break
                clean_line = line.strip()
                if "[download]" in clean_line and "%" in clean_line:
                    short_progress = clean_line.replace("[download]", "").strip().split(" eta ")[0]

                    cols, _ = shutil.get_terminal_size(fallback=(120, 24))
                    prefix = f"[Worker {slot_id + 1}] Task {index}/{total_files}: "
                    suffix = f" - {short_progress}"
                    title_budget = max(cols - len(prefix) - len(suffix), 8)
                    short_title = truncate_to_fit(safe_name, title_budget)

                    status_line = f"{prefix}{short_title}{suffix}"
                    update_worker_slot(slot_id, status_line, total_workers)

        if shutdown_event.is_set():
            return False

        process.wait()
        if process.returncode != 0:
            raise subprocess.CalledProcessError(process.returncode, ytdlp_cmd)

        write_history_line(f"[+] [{index}/{total_files}] Successfully downloaded: {safe_name}")
        update_worker_slot(slot_id, f"[Worker {slot_id + 1}] Idle...", total_workers)
        return True

    except subprocess.CalledProcessError as err:
        write_history_line(f"[-] [{index}/{total_files}] Failed: {safe_name} (Code {err.returncode})")
        update_worker_slot(slot_id, f"[Worker {slot_id + 1}] Idle...", total_workers)
        return False
    except Exception as e:
        if not shutdown_event.is_set():
            write_history_line(f"[-] [{index}/{total_files}] Error: {e}")
            update_worker_slot(slot_id, f"[Worker {slot_id + 1}] Idle...", total_workers)
        return False
    finally:
        with active_processes_lock:
            active_processes.pop(slot_id, None)


def download_assets():
    global worker_statuses
    global DEFAULT_OUTPUT_DIR
    
    # 1. Check if no command-line arguments are provided[cite: 5]
    if len(sys.argv) == 1:
        input_json_path, selection_arg, workers = prompt_for_inputs()
    else:
        # Otherwise parse CLI inputs as usual
        args = parse_arguments()
        
        # If output path is explicitly set via flag, assign it
        if args.output:
            DEFAULT_OUTPUT_DIR = Path(clean_dragged_path(args.output)).expanduser()
            
        # Resolve Input JSON[cite: 5]
        if args.input:
            input_json_path = Path(clean_dragged_path(args.input)).expanduser()
            if not input_json_path.exists():
                print(f"[-] Error: '{input_json_path}' not found. Verify your --input path configuration.")
                return
        else:
            # Simple fallback path prompt if they passed SOME arguments (like -w or -o) but not -i
            input_json_path = prompt_for_input_path()
            
        selection_arg = args.number
        workers = max(1, args.workers if args.workers is not None else 1)

    # Apply global ceiling clamp on concurrency
    MAX_WORKERS = 5
    if workers > MAX_WORKERS:
        print(f"[*] Requested {workers} workers, but the hard cap is {MAX_WORKERS}. Clamping down.")
        workers = MAX_WORKERS

    if not shutil.which("yt-dlp"):
        print("[-] Error: 'yt-dlp' was not found in your system PATH.")
        return

    DEFAULT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print(f"[*] Reading download queue from {input_json_path}...")
    with open(input_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    files_list = data.get("files_found", [])
    if not files_list:
        print("[-] No files found in the download queue configuration.")
        return

    total_files = len(files_list)

    # Build the (original_index, item) work queue. Default: everything.
    indexed_files = list(enumerate(files_list, start=1))
    if selection_arg:
        try:
            selection = parse_selection(selection_arg, total_files)
        except ValueError as exc:
            print(f"[-] Error: {exc}")
            return
        indexed_files = [(idx, item) for idx, item in indexed_files if idx in selection]
        print(f"[*] Selection '{selection_arg}' resolved to {len(indexed_files)} item(s) out of {total_files} total.")

    if not indexed_files:
        print("[-] No items match the given selection.")
        return

    queue_size = len(indexed_files)
    # Workers shouldn't outnumber the actual work queued
    workers = min(workers, queue_size)

    print(f"[+] Found {total_files} potential items in queue; downloading {queue_size} (Concurrency Engine: {workers} workers).\n")
    print("[*] Initializing Multi-Threaded Orchestrator Pool Framework...\n")

    # Reserve the bottom `workers` rows as a fixed footer and confine scrolling
    # to everything above it.
    setup_display_region(workers)

    worker_statuses = [f"[Worker {i + 1}] Idle..." for i in range(workers)]
    for i in range(workers):
        row = TERMINAL_ROWS - workers + i + 1
        sys.stdout.write(f"\033[{row};1H\033[2K{worker_statuses[i]}")
    sys.stdout.flush()

    executor = ThreadPoolExecutor(max_workers=workers)

    available_slots = list(range(workers))
    slot_assignments = {}

    try:
        task_iterator = iter(indexed_files)
        active_futures = []

        while True:
            while available_slots and (file_data := next(task_iterator, None)):
                idx, item = file_data
                slot = available_slots.pop(0)

                f = executor.submit(execute_ytdlp_task, idx, total_files, item, slot, workers)
                slot_assignments[f] = slot
                active_futures.append(f)

            if not active_futures:
                break

            done_batch = []
            for f in as_completed(active_futures):
                done_batch.append(f)
                break

            for f in done_batch:
                active_futures.remove(f)
                slot_freed = slot_assignments.pop(f)
                available_slots.append(slot_freed)
                try:
                    f.result()
                except Exception:
                    pass

    except KeyboardInterrupt:
        # Stop any further display writes immediately -- this must happen
        # before we touch the terminal layout at all, so no worker thread
        # can write to a footer row after we've reset the scroll region.
        shutdown_event.set()

        # Cancel not-yet-started futures, and actually kill the yt-dlp
        # child processes that ARE running
        executor.shutdown(wait=False, cancel_futures=True)
        with active_processes_lock:
            live_processes = list(active_processes.values())
        for proc in live_processes:
            try:
                proc.terminate()
            except Exception:
                pass
        for proc in live_processes:
            try:
                proc.wait(timeout=5)
            except Exception:
                try:
                    proc.kill()
                except Exception:
                    pass

        # Tear down the scroll region safely after child processes are dead.
        teardown_display_region()
        print("[!] Ctrl+C detected! Terminating all background tasks cleanly...")
        sys.exit(130)
    finally:
        if not shutdown_event.is_set():
            executor.shutdown(wait=True)
            teardown_display_region()

    print("\n[+] All queue tasks processed.")


def prompt_for_input_path() -> Path:
    """Fallback interactive prompt if CLI args were passed but input flag was missing."""
    while True:
        raw = Prompt.ask("[bold cyan]Path to the album JSON file[/bold cyan]")
        candidate = Path(clean_dragged_path(raw)).expanduser()
        if candidate.exists() and candidate.is_file():
            return candidate
        print(f"[-] '{candidate}' doesn't exist or isn't a file. Try again.")


if __name__ == "__main__":
    if os.name == 'nt':
        import subprocess
        subprocess.run("", shell=True)

    download_assets()