import json
import argparse
import subprocess
import shutil
import sys
import os
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading

from rich.prompt import Prompt
from rich.console import Console
from rich.progress import (
    Progress,
    TextColumn,
    BarColumn,
    TaskProgressColumn,
    DownloadColumn,
    TransferSpeedColumn,
)

# Paths config
DEFAULT_OUTPUT_DIR = Path.home() / "Downloads" / "bunkr_downloads"

console = Console()

# Live yt-dlp subprocess handles, so an interrupt can actually kill them
# instead of just cancelling futures that haven't started yet.
active_processes_lock = threading.Lock()
active_processes = {}  # slot_id -> Popen

shutdown_event = threading.Event()


def parse_arguments():
    """Parse command line arguments for the downloader script."""
    parser = argparse.ArgumentParser(description="Parallel/Sequential yt-dlp Asset Downloader Queue.")
    parser.add_argument(
        '-i', '--input',
        type=str,
        default=None,
        help=(
            "Path to the enriched album JSON file generated by the scraper. "
            "If omitted, you'll be prompted for it interactively."
        )
    )
    parser.add_argument(
        '-o', '--output',
        type=str,
        default=None,
        help=(
            "Directory to save downloaded files into "
            f"(default: {DEFAULT_OUTPUT_DIR})."
        )
    )
    parser.add_argument(
        '-w', '--workers',
        type=int,
        default=None,  # Set to None to cleanly identify when no CLI argument is given
        help="Number of concurrent download worker threads to spawn."
    )
    parser.add_argument(
        '-n', '--number',
        type=str,
        default=None,
        help=(
            "Restrict the run to specific item(s) from the JSON, by their "
            "1-based position (the same number shown in [n/total] logging). "
            "Accepts a single index ('5'), a comma list ('3,7,12'), a range "
            "('10-20'), or a mix of both ('1,4-6,9'). Omit to download everything."
        )
    )
    return parser.parse_args()


def parse_selection(spec: str, total_files: int) -> set:
    """Parses a -n/--number spec like '1,4-6,9' into a set of 1-based indices."""
    selected = set()
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            start_str, end_str = chunk.split("-", 1)
            start, end = int(start_str), int(end_str)
            if start > end:
                start, end = end, start
            selected.update(range(start, end + 1))
        else:
            selected.add(int(chunk))

    out_of_range = {i for i in selected if i < 1 or i > total_files}
    if out_of_range:
        raise ValueError(
            f"Index/indices {sorted(out_of_range)} out of range "
            f"(file has {total_files} items, valid range is 1-{total_files})."
        )
    return selected


def clean_dragged_path(raw: str) -> str:
    """Normalizes a path typed or drag-and-dropped into the terminal."""
    text = raw.strip()
    if len(text) >= 2 and text[0] == text[-1] and text[0] in ("'", '"'):
        text = text[1:-1].strip()
    text = text.replace("\\ ", " ")
    return text


def prompt_for_input_path() -> Path:
    """Interactively asks for the JSON queue file when --input wasn't supplied."""
    while True:
        raw = Prompt.ask("[bold cyan]Path to the album JSON file[/bold cyan]")
        candidate = Path(clean_dragged_path(raw)).expanduser()
        if candidate.exists() and candidate.is_file():
            return candidate
        console.print(f"[red][-][/red] '{candidate}' doesn't exist or isn't a file. Try again.")


def prompt_for_inputs():
    """
    Scans the working directory for payload JSONs, prints them out cleanly,
    and then prompts the user dynamically for input path, items selection, and workers.
    """
    # 1. Scan and print local .json files
    try:
        json_files = [f for f in os.listdir('.') if f.endswith('.json') and os.path.isfile(f)]
        if json_files:
            console.print("\n[bold magenta][*] Discovered payload JSON targets in working directory:[/bold magenta]")
            for f in sorted(json_files):
                console.print(f"  • [yellow]{f}[/yellow]")
            console.print()
    except Exception as e:
        console.print(f"[bold red][-][/bold red] Warning: Could not scan directory for JSON files: {e}")

    # 2. Prompt for path to the album JSON
    input_path = None
    while True:
        raw = Prompt.ask("[bold cyan][?][/bold cyan] Path to the album JSON file")
        candidate = Path(clean_dragged_path(raw)).expanduser()
        if candidate.exists() and candidate.is_file():
            input_path = candidate
            break
        console.print(f"[bold red][-][/bold red] Error: '{candidate}' doesn't exist or isn't a file. Try again.")

    # 3. Prompt for targeted index selection (subset vs all)
    selection = Prompt.ask(
        "[bold cyan][?][/bold cyan] Enter item index, list, or range [dim](e.g. 5 | 3,7,12 | 1-10 or Press Enter for ALL)[/dim]"
    ).strip()
    if not selection or selection.lower() == 'all':
        selection = None

    # 4. Prompt for worker concurrency
    workers_input = Prompt.ask(
        "[bold cyan][?][/bold cyan] Enter worker concurrency (MAX=5) [dim](Press Enter for default)[/dim]"
    ).strip()

    workers = 1
    if workers_input:
        try:
            workers = max(1, int(workers_input))
        except ValueError:
            console.print("[bold yellow][!][/bold yellow] Invalid worker layout pattern. Defaulting to 1 worker.")
            workers = 1

    return input_path, selection, workers


def sanitize_filename(name: str) -> str:
    """Removes or replaces characters that are illegal in Windows/Linux file systems."""
    return "".join(c for c in name if c.isalnum() or c in "._- ()").strip()


def execute_ytdlp_task(index: int, total_files: int, file_item: dict, slot_id: int,
                        task_id, progress: Progress):
    """
    Assembles and executes the yt-dlp subprocess payload for a specific asset row.
    Reports progress through `progress`/`task_id` instead of raw ANSI writes --
    rich.progress owns the terminal layout, so there's no cursor math here at all.
    """
    title = file_item.get("title", f"file_{index}")
    cdn_url = file_item.get("signed_cdn_url")

    safe_name = sanitize_filename(title)
    dest = DEFAULT_OUTPUT_DIR / safe_name

    def set_idle():
        progress.update(task_id, description=f"[Worker {slot_id + 1}] Idle...", completed=0, total=None)

    if not cdn_url:
        progress.console.print(f"[red][-][/red] [{index}/{total_files}] Skipping: {safe_name} (No active signed URL found)")
        set_idle()
        return False

    ytdlp_cmd = [
        "yt-dlp",
        "--no-playlist",
        "--retries", "50",
        "--fragment-retries", "10",
        "--retry-sleep", "5",
        "--concurrent-fragments", "1",
        "--socket-timeout", "25",
        "--continue",
        "--newline",
        "--referer", "https://bunkr.cr/",
        "--add-header", "Origin:https://bunkr.cr",
        "--add-header", (
            "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "--add-header", "Accept-Encoding:identity",
        "--progress-template", "download:PROGRESS %(progress.downloaded_bytes)s %(progress.total_bytes)s",
        "-o", str(dest),
        cdn_url,
    ]

    progress.update(task_id, description=f"[Worker {slot_id + 1}] Task {index}/{total_files}: {safe_name}",
                     completed=0, total=None)

    process = None
    try:
        process = subprocess.Popen(ytdlp_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, encoding="utf-8")
        with active_processes_lock:
            active_processes[slot_id] = process

        if process.stdout:
            for line in process.stdout:
                if shutdown_event.is_set():
                    break
                clean_line = line.strip()
                if clean_line.startswith("PROGRESS "):
                    parts = clean_line.split()
                    if len(parts) == 3:
                        _, downloaded_str, total_str = parts
                        try:
                            downloaded_bytes = int(downloaded_str)
                            total_bytes = int(total_str)
                            # total_bytes can arrive as "NA" (size unknown until
                            # download starts) -- int() raising ValueError just
                            # skips that tick rather than showing bogus units.
                            progress.update(task_id, completed=downloaded_bytes, total=total_bytes)
                        except ValueError:
                            pass

        if shutdown_event.is_set():
            return False

        process.wait()
        if process.returncode != 0:
            raise subprocess.CalledProcessError(process.returncode, ytdlp_cmd)

        progress.console.print(f"[green][+][/green] [{index}/{total_files}] Successfully downloaded: {safe_name}")
        set_idle()
        return True

    except subprocess.CalledProcessError as err:
        progress.console.print(f"[red][-][/red] [{index}/{total_files}] Failed: {safe_name} (Code {err.returncode})")
        set_idle()
        return False
    except Exception as e:
        if not shutdown_event.is_set():
            progress.console.print(f"[red][-][/red] [{index}/{total_files}] Error: {e}")
            set_idle()
        return False
    finally:
        with active_processes_lock:
            active_processes.pop(slot_id, None)


def download_assets():
    global DEFAULT_OUTPUT_DIR

    # 1. Check if no command-line arguments are provided
    if len(sys.argv) == 1:
        input_json_path, selection_arg, workers = prompt_for_inputs()
    else:
        # Otherwise parse CLI inputs as usual
        args = parse_arguments()

        # If output path is explicitly set via flag, assign it
        if args.output:
            DEFAULT_OUTPUT_DIR = Path(clean_dragged_path(args.output)).expanduser()

        # Resolve Input JSON
        if args.input:
            input_json_path = Path(clean_dragged_path(args.input)).expanduser()
            if not input_json_path.exists():
                console.print(f"[red][-][/red] Error: '{input_json_path}' not found. Verify your --input path configuration.")
                return
        else:
            # Simple fallback path prompt if they passed SOME arguments (like -w or -o) but not -i
            input_json_path = prompt_for_input_path()

        selection_arg = args.number
        workers = max(1, args.workers if args.workers is not None else 1)

    # Apply global ceiling clamp on concurrency
    MAX_WORKERS = 5
    if workers > MAX_WORKERS:
        console.print(f"[*] Requested {workers} workers, but the hard cap is {MAX_WORKERS}. Clamping down.")
        workers = MAX_WORKERS

    if not shutil.which("yt-dlp"):
        console.print("[red][-][/red] Error: 'yt-dlp' was not found in your system PATH.")
        return

    DEFAULT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    console.print(f"[*] Reading download queue from {input_json_path}...")
    with open(input_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    files_list = data.get("files_found", [])
    if not files_list:
        console.print("[red][-][/red] No files found in the download queue configuration.")
        return

    total_files = len(files_list)

    indexed_files = list(enumerate(files_list, start=1))
    if selection_arg:
        try:
            selection = parse_selection(selection_arg, total_files)
        except ValueError as exc:
            console.print(f"[red][-][/red] Error: {exc}")
            return
        indexed_files = [(idx, item) for idx, item in indexed_files if idx in selection]
        console.print(f"[*] Selection '{selection_arg}' resolved to {len(indexed_files)} item(s) out of {total_files} total.")

    if not indexed_files:
        console.print("[red][-][/red] No items match the given --number selection.")
        return

    queue_size = len(indexed_files)
    workers = min(workers, queue_size)

    console.print(f"[+] Found {total_files} potential items in queue; downloading {queue_size} (Concurrency Engine: {workers} workers).\n")

    progress = Progress(
        TextColumn("{task.description}"),
        BarColumn(bar_width=40, style="grey35", complete_style="cyan", finished_style="green"),
        TaskProgressColumn(),
        DownloadColumn(),
        TransferSpeedColumn(),
        console=console,
    )

    executor = ThreadPoolExecutor(max_workers=workers)
    available_slots = list(range(workers))
    slot_assignments = {}

    with progress:
        # One persistent task/bar per worker slot, reused across files.
        slot_task_ids = [
            progress.add_task(f"[Worker {i + 1}] Idle...", total=None, completed=0)
            for i in range(workers)
        ]

        try:
            task_iterator = iter(indexed_files)
            active_futures = []

            while True:
                while available_slots and (file_data := next(task_iterator, None)):
                    idx, item = file_data
                    slot = available_slots.pop(0)

                    f = executor.submit(
                        execute_ytdlp_task, idx, total_files, item, slot,
                        slot_task_ids[slot], progress
                    )
                    slot_assignments[f] = slot
                    active_futures.append(f)

                if not active_futures:
                    break

                done_batch = []
                for f in as_completed(active_futures):
                    done_batch.append(f)
                    break

                for f in done_batch:
                    active_futures.remove(f)
                    slot_freed = slot_assignments.pop(f)
                    available_slots.append(slot_freed)
                    try:
                        f.result()
                    except Exception:
                        pass

        except KeyboardInterrupt:
            shutdown_event.set()
            executor.shutdown(wait=False, cancel_futures=True)
            with active_processes_lock:
                interrupted_slots = list(active_processes.items())  # [(slot_id, proc), ...]
            for _, proc in interrupted_slots:
                try:
                    proc.terminate()
                except Exception:
                    pass
            for _, proc in interrupted_slots:
                try:
                    proc.wait(timeout=5)
                except Exception:
                    try:
                        proc.kill()
                    except Exception:
                        pass

            # Mark any mid-download worker rows as interrupted instead of
            # leaving them frozen on a stale byte count/percentage.
            for slot_id, _ in interrupted_slots:
                progress.update(
                    slot_task_ids[slot_id],
                    description=f"[Worker {slot_id + 1}] Interrupted",
                    completed=0, total=None,
                )

            # Stop the Live display explicitly, BEFORE printing the shutdown
            # message. Live keeps a background thread repainting the worker
            # rows several times a second until it's stopped -- printing
            # first and relying on `with progress:` to stop it on exit left
            # a window where that thread redrew a stale row underneath our
            # message. Stopping it here closes that window.
            progress.stop()
            console.print("\n[yellow][![/yellow] Ctrl+C detected! Terminating all background tasks cleanly...")
            sys.exit(130)
        finally:
            if not shutdown_event.is_set():
                executor.shutdown(wait=True)

    console.print("\n[+] All queue tasks processed.")


if __name__ == "__main__":
    if os.name == 'nt':
        import subprocess
        subprocess.run("", shell=True)

    download_assets()