import json
import argparse
import urllib.parse
from pathlib import Path
from datetime import datetime, timedelta
from curl_cffi import requests
import urllib3

# Bring in rich components for a consistent UI layout
from rich.console import Console
from rich.progress import Progress, TextColumn, BarColumn, TaskProgressColumn, TimeRemainingColumn

# Suppress insecure request warnings from verify=False to prevent console clutter
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

console = Console()

def parse_arguments():
    """Parse command line arguments for the signature minter script."""
    parser = argparse.ArgumentParser(description="CDN Token Signature Minter Utility.")
    parser.add_argument(
        '-i', '--input',
        type=str,
        default="album_files.json",
        help="Path to the album JSON file generated by the scraper (default: album_files.json)."
    )
    return parser.parse_args()

def mint_cdn_url(session, file_id):
    """
    Executes the two-step handshake via curl_cffi to fetch metadata 
    and sign the CDN path for a specific true_file_id.
    """
    headers = {
        "Content-Type": "application/json",
        "Origin": "https://dl.bunkr.cr",
        "Referer": f"https://dl.bunkr.cr/file/{file_id}",
    }
    
    # --- Step 1: Query Metadata API ---
    meta_url = "https://dl.bunkr.cr/api/_001_v2"
    payload = {"id": file_id}
    
    try:
        meta_res = session.post(meta_url, json=payload, headers=headers, verify=False)
        meta_res.raise_for_status()
        meta_data = meta_res.json()
        
        cdn_host = meta_data["mediafiles"]
        storage_path = meta_data["path"]
        original_name = meta_data["original"]
    except Exception as e:
        console.print(f"    [bold red][-][/bold red] Metadata lookup failed for ID [dim]{file_id}[/dim]: {e}")
        return None

    # --- Step 2: Request Dynamic Validation Token ---
    encoded_path = urllib.parse.quote(storage_path)
    sign_url = f"https://glb-apisign.cdn.cr/sign?path={encoded_path}"
    
    try:
        sign_res = session.get(sign_url, headers=headers)
        sign_res.raise_for_status()
        sign_data = sign_res.json()
        
        token = sign_data["token"]
        ex = sign_data["ex"]
    except Exception as e:
        console.print(f"    [bold red][-][/bold red] Token signature generation failed for ID [dim]{file_id}[/dim]: {e}")
        return None

    # --- Step 3: Stitch Final Signed URL ---
    encoded_name = urllib.parse.quote(original_name)
    final_cdn_url = f"{cdn_host}{storage_path}?n={encoded_name}&token={token}&ex={ex}"
    return final_cdn_url

def batch_process_signatures():
    args = parse_arguments()
    input_json_path = Path(args.input)

    if not input_json_path.exists():
        console.print(f"[bold red][-][/bold red] Error: Could not find '[bold white]{input_json_path}[/bold white]'. Verify your --input configuration.")
        return

    console.print(f"[bold yellow][*][/bold yellow] Loading database file targets from [dim white]{input_json_path}[/dim white]...")
    with open(input_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    files_list = data.get("files_found", [])
    if not files_list:
        console.print("[bold red][-][/bold red] No items found in the 'files_found' key inside the JSON structure.")
        return

    total_files = len(files_list)
    console.print(f"[bold green][+][/bold green] Loaded [bold cyan]{total_files}[/bold cyan] file entries for token minting.\n")

    minted_count = 0

    # Custom Progress Bar configuration columns
    progress_bar = Progress(
        TextColumn("[bold yellow][*][/bold yellow] Minting tokens..."),
        BarColumn(bar_width=40, style="dim white", complete_style="green"),
        TaskProgressColumn(),
        TimeRemainingColumn(),
        console=console
    )

    # Use a robust Context Manager to maintain session state
    with requests.Session(impersonate="chrome") as session, progress_bar:
        # Register task inside tracking bar matrix
        task_id = progress_bar.add_task("Processing", total=total_files)

        for file_item in files_list:
            file_id = file_item.get("true_file_id")
            title = file_item.get("title", "Unknown")
            
            if not file_id:
                # Log cleanly directly over the tracking bar without clearing screen
                progress_bar.console.print(f"  [bold yellow][!][/bold yellow] Skipping [dim white]'{title[:40]}'[/dim white] - Missing true_file_id.")
                file_item["signed_cdn_url"] = None
                progress_bar.advance(task_id)
                continue
                
            signed_url = mint_cdn_url(session, file_id)
            
            if signed_url:
                file_item["signed_cdn_url"] = signed_url
                minted_count += 1
            else:
                file_item["signed_cdn_url"] = None
            
            # Step progress state machine forward by one tick iteration
            progress_bar.advance(task_id)

    # Update structural parent map object
    data["files_found"] = files_list

    # Save out the enriched JSON mapping array back to the input path target
    console.print(f"\n[bold yellow][*][/bold yellow] Writing enriched URLs back to [dim white]{input_json_path}[/dim white]...")
    with open(input_json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        
    console.print(f"[bold green][+][/bold green] Complete! Successfully minted tokens for [bold cyan]{minted_count}/{total_files}[/bold cyan] assets.")

    # =========================================================================
    # EXPIRATION WARNING WINDOW
    # =========================================================================
    if minted_count > 0:
        # Calculate approximate expiration (2 hours from current local execution time)
        expiry_time = datetime.now() + timedelta(hours=2)
        formatted_expiry = expiry_time.strftime("%I:%M %p (%Y-%m-%d)")
        
        console.print("  The signed tokens injected into the JSON file have a limited lifetime.")
        console.print("  These temporary links will completely expire in exactly [bold yellow]2 hours[/bold yellow].")
        console.print(f"  You have up to [bold yellow]{formatted_expiry}[/bold yellow] to use these links.")
        
if __name__ == "__main__":
    batch_process_signatures()