import argparse
import json
import shutil
import subprocess
from pathlib import Path

# Paths config
DEFAULT_OUTPUT_DIR = Path.home() / "Downloads" / "bunkr_downloads"
DEFAULT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def parse_arguments():
    """Parse command line arguments for the downloader script."""
    parser = argparse.ArgumentParser(description="Parallel/Sequential yt-dlp Asset Downloader Queue.")
    parser.add_argument(
        '-i', '--input',
        type=str,
        default="album_files.json",
        help="Path to the enriched album JSON file generated by the scraper (default: album_files.json)."
    )
    return parser.parse_args()

def sanitize_filename(name: str) -> str:
    """Removes or replaces characters that are illegal in Windows/Linux file systems."""
    return "".join(c for c in name if c.isalnum() or c in "._- ()").strip()

def download_assets():
    # Parse incoming dynamic target arguments
    args = parse_arguments()
    input_json_path = Path(args.input)

    # Verify yt-dlp is available in the environment path
    if not shutil.which("yt-dlp"):
        print("[-] Error: 'yt-dlp' was not found in your system PATH.")
        return

    if not input_json_path.exists():
        print(f"[-] Error: '{input_json_path}' not found. Verify your --input path argument configuration.")
        return

    print(f"[*] Reading download queue from {input_json_path}...")
    with open(input_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    files_list = data.get("files_found", [])
    if not files_list:
        print("[-] No files found in the download queue configuration.")
        return

    total_files = len(files_list)
    print(f"[+] Found {total_files} potential items to download.\n")

    for index, file_item in enumerate(files_list, start=1):
        title = file_item.get("title", f"file_{index}")
        cdn_url = file_item.get("signed_cdn_url")
        
        if not cdn_url:
            print(f"[{index}/{total_files}] Skipping '{title[:40]}' - No active signed URL found.")
            continue

        # Sanitize name directly as provided in the JSON payload
        safe_name = sanitize_filename(title)
        dest = DEFAULT_OUTPUT_DIR / safe_name
        
        print(f"[{index}/{total_files}] Starting download for: {safe_name}")
        print(f"    -> Saving to: {dest}")

        # Assemble your verified yt-dlp arguments configuration
        ytdlp_cmd = [
            "yt-dlp", 
            "--no-playlist",
            "--retries", "50",
            "--fragment-retries", "10",
            "--retry-sleep", "5",
            "--concurrent-fragments", "1",                      
            "--socket-timeout", "25",                    
            "--continue",
            "--referer", "https://bunkr.cr/",
            "--add-header", "Origin:https://bunkr.cr",
            "--add-header", (
                "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
            "--add-header", "Accept-Encoding:identity",  
            "-o", str(dest),
            cdn_url,
        ]

        try:
            # Runs the subprocess synchronously, streaming stdout/stderr back to your shell console window
            result = subprocess.run(ytdlp_cmd, check=True)
            if result.returncode == 0:
                print(f"[+] Successfully downloaded: {safe_name}\n")
        except subprocess.CalledProcessError as err:
            print(f"[-] yt-dlp failed downloading '{safe_name}'. Exit code: {err.returncode}\n")
        except Exception as e:
            print(f"[-] Unexpected script exception during execution: {e}\n")

    print("[+] All queue tasks processed.")

if __name__ == "__main__":
    download_assets()