import argparse
import json
import urllib.parse
from pathlib import Path

from curl_cffi import requests


def parse_arguments():
    """Parse command line arguments for the signature minter script."""
    parser = argparse.ArgumentParser(description="CDN Token Signature Minter Utility.")
    parser.add_argument(
        '-i', '--input',
        type=str,
        default="album_files.json",
        help="Path to the album JSON file generated by the scraper (default: album_files.json)."
    )
    return parser.parse_args()

def mint_cdn_url(session, file_id):
    """
    Executes the two-step handshake via curl_cffi to fetch metadata 
    and sign the CDN path for a specific true_file_id.
    """
    headers = {
        "Content-Type": "application/json",
        "Origin": "https://dl.bunkr.cr",
        "Referer": f"https://dl.bunkr.cr/file/{file_id}",
    }
    
    # --- Step 1: Query Metadata API ---
    meta_url = "https://dl.bunkr.cr/api/_001_v2"
    payload = {"id": file_id}
    
    try:
        meta_res = session.post(meta_url, json=payload, headers=headers, verify=False)
        meta_res.raise_for_status()
        meta_data = meta_res.json()
        
        cdn_host = meta_data["mediafiles"]
        storage_path = meta_data["path"]
        original_name = meta_data["original"]
    except Exception as e:
        print(f"    [-] Metadata lookup failed for ID {file_id}: {e}")
        return None

    # --- Step 2: Request Dynamic Validation Token ---
    encoded_path = urllib.parse.quote(storage_path)
    sign_url = f"https://glb-apisign.cdn.cr/sign?path={encoded_path}"
    
    try:
        sign_res = session.get(sign_url, headers=headers)
        sign_res.raise_for_status()
        sign_data = sign_res.json()
        
        token = sign_data["token"]
        ex = sign_data["ex"]
    except Exception as e:
        print(f"    [-] Token signature generation failed for ID {file_id}: {e}")
        return None

    # --- Step 3: Stitch Final Signed URL ---
    encoded_name = urllib.parse.quote(original_name)
    final_cdn_url = f"{cdn_host}{storage_path}?n={encoded_name}&token={token}&ex={ex}"
    return final_cdn_url

def batch_process_signatures():
    # Parse dynamic target configuration
    args = parse_arguments()
    input_json_path = Path(args.input)

    if not input_json_path.exists():
        print(f"[-] Error: Could not find '{input_json_path}'. Verify your --input path argument configuration.")
        return

    print(f"[*] Loading database file targets from {input_json_path}...")
    with open(input_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    files_list = data.get("files_found", [])
    if not files_list:
        print("[-] No items found in the 'files_found' key inside the JSON structure.")
        return

    total_files = len(files_list)
    print(f"[+] Loaded {total_files} file entries for minting tokens.")

    # Initialize session impersonating Chrome to handle JA3/TLS fingerprints cleanly
    session = requests.Session(impersonate="chrome")
    minted_count = 0

    for index, file_item in enumerate(files_list, start=1):
        file_id = file_item.get("true_file_id")
        title = file_item.get("title", "Unknown")
        
        if not file_id:
            print(f"  [{index}/{total_files}] Skipping '{title[:40]}' - Missing true_file_id.")
            file_item["signed_cdn_url"] = None
            continue
            
        print(f"  [{index}/{total_files}] Minting signed token for: {title[:40]} [ID: {file_id}]")
        
        signed_url = mint_cdn_url(session, file_id)
        
        if signed_url:
            file_item["signed_cdn_url"] = signed_url
            minted_count += 1
        else:
            file_item["signed_cdn_url"] = None

    # Update structural parent map object
    data["files_found"] = files_list

    # Save out the enriched JSON mapping array to the targeted input path
    print(f"\n[*] Writing enriched URLs back to {input_json_path}...")
    with open(input_json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        
    print(f"[+] Complete! Successfully minted signatures for {minted_count}/{total_files} assets.")

if __name__ == "__main__":
    batch_process_signatures()